### ISSUE TITLE
Another pipeline?

### ISSUE THREAD

**Issue by Isabelle-Simard** [mtl-brainhack-school-2019/iron-meta-pipeline#1]
This is a very good idea! I haven't tried to run DTI analysis yet but I have looked into it before. I was really annoyed by how people were recommending combining the different steps of different toolboxes which can get really confusing and require many format conversions. I really support your project! I can't wait to see the results.

**Comment by matteomancini** [comment]
Thanks! (: It is quite common that the tools used in most diffusion studies are publicly available, but the combinations of those and the different parameters contribute to an overall nightmare if you want to replicate their pipelines!
