### ISSUE TITLE
Alternatives to build pipelines for tractography

### ISSUE THREAD

**Issue by matteomancini** [mtl-brainhack-school-2019/iron-meta-pipeline#3]
@PeerHerholz given that you work with tractography, I wanted to ask if you actually have seen tools that allow you to build modular pipelines. So far, apart from what you can do with Nipype, I couldn't find anything specific, the only similar thing is TractoFlow, based on Nextflow, but it is more of a specific pipeline rather than a tool to implement several pipelines.

**Comment by alexapichet** [comment]
Highly recommend using TractoFlow if you want to preprocess your diffusion data!

**Comment by PeerHerholz** [comment]
Less "work", more "playing around", but `nipype` is a good starting point. [It supports dipy to quite some extent](https://github.com/nipy/nipype/tree/master/nipype/interfaces/dipy). If you're interested in building modular pipelines, it would be cool to use [niflows](https://github.com/niflows) (intro [here](https://effigies.github.io/niflows-intro/#1)). There's also [dmriprep](https://github.com/nipy/dmriprep) which could be interesting. [Porcupine within Giraffe tools](https://giraffe.tools/porcupine/TimVanMourik/GiraffePlayground/master) could also be extended respectively.

**Comment by matteomancini** [comment]
@alexapichet thank you for the suggestion, I checked it out and it is interesting, I am thinking of implementing that pipeline in trampolino.
@PeerHerholz niflows seems an ideal next step for my application, so definitely future work, thank you for the suggestion!
