### ISSUE TITLE
Iterables for ensemble tractography

### ISSUE THREAD

**Issue by matteomancini** [mtl-brainhack-school-2019/iron-meta-pipeline#5]
@emdupre I wanted to ask you about iterables and Nipype, do you think it is a good way to implement ensemble tractography? Basically in order to combine together different tracking algorithms I was thinking of using Nipype iterables and generate nodes for each algorithm.

**Comment by emdupre** [comment]
What exactly is it that you want to iterate through ? Files ?

PS: The best iterables introduction I've seen (still) is [here](http://miykael.github.io/nipype-beginner-s-guide/firstSteps.html#iterables) !

**Comment by matteomancini** [comment]
Hi Elizabeth, sorry for not getting back to you on this and thank you for the support in person (: As it should be cleared from the final report, I used iterables for using different angular thresholds and algorithms for tractography.
